name: code-runner Image CI

on:
  push:
    branches:
      - main
    paths:
      - "lms/lmsbackend/coderunnerservice/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Create file appication.yml
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "application.yml"
          fileDir: "./lms/lmsbackend/coderunnerservice/src/main/resources/"
          encodedString: ${{ secrets.CODE_RUNNER_B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/code-runner
          directory: "lms/lmsbackend/coderunnerservice/"
          registry: docker.io
          dockerfile: "lms/lmsbackend/coderunnerservice/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./lms/lmsbackend/coderunnerservice/src/main/resources/application.yml"
